### PR TITLE
Port to Python

### PR DESCRIPTION
**Pull request by s-kganz**
Hello,

I ported this package to the earth engine Python API so I could run batch exports more easily. Making a PR in case someone else finds it useful. You can verify that the results are the same between the JS and Python versions.

https://gist.github.com/s-kganz/8f56e3d64efee8f46c0971304e1e4198

### CODE REVIEW

**Comment by zecojls** [comment]
Hey @s-kganz , thanks for this great contribution.

I'm wondering if you could help again by creating a minimal reproducible example using the TAGEE.py and Google Colab (directly in the README), as I'm not proficient with the Python API. This could help other people potentially interested in TAGEE.

Anyway, thank you so much for your collaboration.

**Comment by zecojls** [comment]
@Biku247 Check this demo on Google Colab: [tagee_google_colab.ipynb](https://github.com/zecojls/tagee/blob/9f0e0a512ff4b69cd52fdc62ce7b8a8eb412d208/tagee_google_colab.ipynb)

**Comment by s-kganz** [comment]
Hi @zecojls, glad to hear you found this useful. I could add an example snippet to the readme, but I think it would make more sense to put TAGEE together as a standalone Python package on pypi.org. That way, a user can run `pip install tagee` and then `import tagee` in their scripts. This is a little more convenient than downloading the Python file off of GitHub and would make TAGEE most visible to Python users of earth engine.

I can set the package up on my fork, and of course you would be credited as the primary author (all I did was change syntax around anyway). I'll make another PR when I get that done.

**Comment by zecojls** [comment]
Great idea, @s-kganz, this makes a lot o more sense for python users. Really appreciate your help.

**Pull request merged**
