### PR TITLE
Make code follow GEE's Coding Best Practice

### PR DESCRIPTION
**Pull request by epn09**
* It is suggested that `clip()` should not be used when not necessary. <https://developers.google.com/earth-engine/guides/best_practices#if_you_dont_need_to_clip_dont_use_clip>
* Just clipping once before returning the result is enough as the bounding box will be propagated backwards in the computation chain.
* This PR removes all the intermediate `clip` and perform only one `clip` in the end.
* According to the link above, it may reduce computational time.

### CODE REVIEW

**Comment by s-kganz** [comment]
Hi @epn09, thanks for the contribution and sorry for being slow to respond. This looks like a good idea. I made a PR to your branch that makes similar changes to the JS version and updates the readme (I don't have write access to this repo so I couldn't commit on top of this PR). If you merge that (and perhaps make another PR?) then this should be good to go.

@zecojls, what do you think?

**Comment by epn09** [comment]
@s-kganz 
Thanks for responding. 
I have checked your PR (https://github.com/epn09/tagee/pull/1).
If @zecojls also agrees to remove `bbox` entirely at the risk of breaking existing code then I'll merge it.

**Comment by zecojls** [comment]
Hi all, I was on vacation last week and away from my computer. Glad to see that @s-kganz has helped Raul with his issue and also see this PR for improving the algorithm. This looks like the way to go, we just need to confirm if the code won't corrupt. Thank you @epn09.


PS: @s-kganz I'm adding you as a repo maintainer so you can also help me to sort out things quickly...

**Comment by zecojls** [comment]
Ok, I just checked everything and it won't break in JS and Py. However, if we remove entirely the bbox call it won't be compatible with the previous versions, breaking the current code of folks. I liked that @epn09 kept bbox call for reverse compatibility, but it is really not necessary anymore (@s-kganz removed from the forked version). What do you suggest? Remove completely or keep minimum compatibility?

If we remove we should version it to v2.0 as it is a major change. We need to keep a heads-up on top of the readme.

**Comment by s-kganz** [comment]
Hi @zecojls, thanks for merging in @epn09's PR. On second thought I think it is a good idea to leave `bbox` as a parameter in `terrainAnalysis`. This is a small package so I think it makes sense to have minimal issues with backwards compatibility. Later today I will make a commit to bump the package information and get it up on PyPI.

**Comment by zecojls** [comment]
Perfect, the `readme` and JS code were updated. Please, just make the necessary changes to deploy on PyPI...

**Pull request merged**
